/-
BRIDGE-INFEASIBILITY PROBE (ROUND-2026-07-14, Task A / WS2) — EXPECTED TO TIME OUT.

This file records, reproducibly, WHY the kernel-pure `lrat_proof` route (validated
axiom-clean in Demo.lean) cannot be bridged back to `primFacts`'s `(MCNF 9 18).Unsat`
without native_decide.

Any such bridge must, at some point, have the KERNEL check that our CNF (the thing
`primFacts` reasons about) equals the CNF the certificate refutes. That forces the
kernel to reduce `MCNF 9 18` — which is generated by `List.sublistsLen` over
`List.finRange 9` (C(9,3)+C(9,5)+C(9,6)·C(15,12)+card = 39743 clauses). Even the
cheapest possible probe of that reduction, just its LENGTH, does not finish:

    set_option maxRecDepth 1000000 in
    example : (MCNF 9 18).clauses.size = 39743 := by rfl     -- TIMES OUT >400s

Run (expect a >400s hang / your `timeout` to fire):
    cd lean617 && timeout 420 lake env lean KernelPureDemo/BridgeInfeasibilityProbe.lean

This is the same reason the graph/primitive facts use `native_decide` in the first
place: these `Finset`/`sublistsLen` objects are not kernel-reducible at this scale.
A kernel-pure SAT integration would require reimplementing PrimEncoding in a
kernel-reducible form AND a proof-producing checker over it — out of scope for this
round. See FORMAL.md "KERNEL-PURE MIGRATION".
-/
import Lean617.PrimEncoding
open Erdos617F3

set_option maxHeartbeats 4000000 in
set_option maxRecDepth 1000000 in
example : (MCNF 9 18).clauses.size = 39743 := by rfl
