/-
KERNEL-PURE SAT DEMONSTRATION (ROUND-2026-07-14, Task A / WS2).

This standalone file (NOT part of the `Lean617` library — `lake build` does not
touch it) demonstrates that the SAT primitive M9's unsatisfiability has a genuinely
KERNEL-CHECKED, axiom-pure proof via Mathlib's `lrat_proof` (`Mathlib.Tactic.Sat.FromLRAT`).
`lrat_proof` replays the LRAT certificate by BUILDING A PROOF TERM that the Lean
kernel typechecks — no `native_decide`, no `ofReduceBool`.

Run:  cd lean617 && lake env lean KernelPureDemo/Demo.lean

Expected `#print axioms m9_kernel_pure`:
    'm9_kernel_pure' depends on axioms: [propext, Classical.choice, Quot.sound]
i.e. ZERO reflection axioms — the certificate is checked by the kernel alone.

PROVENANCE of the two assets (both regenerable, exact commands):
  * M9.cnf       — the canonical DIMACS emitted from the Lean definition `MCNF 9 18`
                   (sha256 596ffcfbfcb709d691a6d97fed415ce7d015f64f95c48cf963cbeb9be9d618cb,
                   matches tools/certgen/checksums.txt). Regenerate:
                     lake env lean --run ../tools/certgen/emit_cnf.lean M 9 18 M9.cnf
  * M9.core.lrat — a fresh CaDiCaL 3.0.0 re-solve, backward-trimmed to the UNSAT
                   core by our ext/drat-trim (17010 core lemmas, gapped ids — fine
                   for `lrat_proof`, which keys clauses by stated id):
                     cadical M9.cnf M9.drat --binary=false --quiet --unsat --inprocessing=false
                     ext/drat-trim/drat-trim M9.cnf M9.drat -L M9.core.lrat   # "s VERIFIED"

MEASURED COST (this machine, 64GB): 495s wall, 14.0GB peak, for M9's 17010-lemma core.

WHY THIS IS NOT (YET) WIRED INTO `primFacts`. `primFacts` consumes `(MCNF 9 18).Unsat`
(our `Std.Sat.CNF.Unsat`). Bridging `lrat_proof`'s theorem to that shape requires the
kernel to MATERIALIZE our CNF (`MCNF`/`nonexCNF`, generated by `List.sublistsLen` over
`List.finRange`) and match it to the certificate's CNF. That reduction is infeasible in
the kernel: `example : (MCNF 9 18).clauses.size = 39743 := by rfl` TIMES OUT at >400s even
with `maxRecDepth 1000000` — the identical obstruction that made `native_decide` necessary
for the primitives in the first place. And even setting the bridge aside, the two large
primitives are out of reach on memory: nonex11/nonex12 have 325MB/455MB raw certificates
(hundreds of thousands of lemmas) while M9's mere 17010 lemmas already cost 14GB here.
So the four SAT primitives retain `native_decide` (see FORMAL.md "KERNEL-PURE MIGRATION"
and tools/axiom_allowlist.txt for the exact accounting). This file is the end-to-end
validation that the kernel route itself is sound and axiom-clean at the scale it can reach.
-/
import Mathlib.Tactic.Sat.FromLRAT

-- `m9_kernel_pure`: kernel-checked UNSAT of the M9 CNF (α≤2, ω≤4, cap-11, ≤18 edges on
-- 9 vertices), via Mathlib's proof-term-producing LRAT replay. Axiom-pure.
-- (`lrat_proof` is a command, so no `/-- -/` doc-comment may precede it.)
lrat_proof m9_kernel_pure
  (include_str "M9.cnf")
  (include_str "M9.core.lrat")

#print axioms m9_kernel_pure
